### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [oscarjes/BanhMi362#1]
Thanks for a fantastic submission. If you don't mind, I'd like to add this to the list of inspiring submissions for future classes :)

## Great things:

- Clear commit messages
- Clear routes with the use of RESTful routes, nested routes, custom action inside member block
- Great use of view helpers that you define in application_helper.rb
- Nice job taking advantage of the DELETE link for deleting a line item
- Deployed to Heroku

## Suggestions

- Change `dependent: :destroy` to `dependent: :nullify` in `cart.rb`'s `has_many :line_items` -- we may want to delete a Cart but we want to keep the line items around because they link past orders with food items.
- To calculate the total price in Cart and Order, define a `LineItem#total_price` so that the following line of code can be improved

```ruby
# before
ordertotal = line_items.sum { |p| p.food_item.price * p.quantity }

# after
order_total = line_items.sum {|line| line.total_price}
```

- There's a syntax error in CartsController (see the extra `def`)
- Consider adding validation to the Order model and add the error handling logic to OrdersController. Ideally, it should let the fix an incomplete form such as incorrect email or phone number.
- Why do you display flash messages (if present) in `sections/index.html.erb` instead of doing that for all pages in `app/views/layouts/application.html.erb`?

Overall, congrats on such a great visual and great code style!

**Comment by oscarjes** [comment]
Thank you for the feedback! 

Of course, I'd love it if it's added to the list of submissions for future classes.
